version: "3.8"
name: local-connector
services:
  provider-connector:
    image: local-connector
    build:
      context: ../src/launcher
      args:
        JAR: build/libs/connector.jar
      dockerfile: Dockerfile
      
    depends_on:
      - postgresql-provider
    environment:
      EDC_FS_CONFIG: /app/configuration.properties
      EDC_API_ASSET_COLLECTOR_FILE: /app/api_collection.json
      EDC_API_AUTH_KEY: "fifi-info-zaneta"
      
    ports:
      - '19191:19191'
      - '19192:19192'
      - '19193:19193'
      - '19194:19194'
      - '19291:19291'
    
    volumes:
      - ../src/launcher/config/configuration-provider.properties:/app/configuration.properties:ro
      - ../src/launcher/config/keystore.pfx:/app/keystore.pfx:ro
      - ../src/launcher/config/fs-provider.vault:/app/fs.vault
      - ../src/launcher/config/api_collection.json:/app/api_collection.json
      - ../src/launcher/config/json_example.json:/app/json_example.json

  consumer-connector:
    image: local-connector
    build:
      context: ../src/launcher
      args:
        JAR: build/libs/connector.jar
      dockerfile: Dockerfile
      
    depends_on:
      - postgresql-consumer
    environment:
      EDC_FS_CONFIG: /app/configuration.properties
      EDC_API_AUTH_KEY: "fifi-info-zaneta"
      
    ports:
      - '29191:29191'
      - '29192:29192'
      - '29193:29193'
      - '29194:29194'
      - '29291:29291'
    
    volumes:
      - ../src/launcher/config/configuration-consumer.properties:/app/configuration.properties:ro
      - ../src/launcher/config/keystore.pfx:/app/keystore.pfx:ro
      - ../src/launcher/config/fs-consumer.vault:/app/fs.vault

  postgresql-provider:
    image: docker.io/bitnami/postgresql:11
    restart: always
    environment:
      POSTGRESQL_USERNAME: edc
      POSTGRESQL_PASSWORD: edc
      POSTGRESQL_DATABASE: edc
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql-provider:/bitnami/postgresql'

  postgresql-consumer:
    image: docker.io/bitnami/postgresql:11
    restart: always
    environment:
      POSTGRESQL_USERNAME: edc
      POSTGRESQL_PASSWORD: edc
      POSTGRESQL_DATABASE: edc
    ports:
      - '5433:5432'
    volumes:
      - 'postgresql-consumer:/bitnami/postgresql'

volumes:
  postgresql-provider:
    driver: local
  postgresql-consumer:
    driver: local