version: "3.8"
name: local-connector
services:
  provider-connector:
    image: local-connector
    build:
      context: ../src/launchers/default
      args:
        JAR: build/libs/connector.jar
      dockerfile: Dockerfile
      
    environment:
      EDC_FS_CONFIG: /app/configuration.properties
      EDC_API_ASSET_COLLECTOR_FILE: /app/api_collection.json
      EDC_API_AUTH_KEY: "fifi-info-zaneta"
      
    ports:
      - '19191:19191'
      - '19192:19192'
      - '19193:19193'
      - '19194:19194'
      - '19291:19291'
    
    volumes:
      - ../src/launchers/default/config/configuration-provider.properties:/app/configuration.properties:ro
      - ../src/launchers/default/config/keystore.pfx:/app/keystore.pfx:ro
      - ../src/launchers/default/config/fs-provider.vault:/app/fs.vault
      - ../src/launchers/default/config/api_collection.json:/app/api_collection.json
      - ../src/launchers/default/config/json_example.json:/app/json_example.json

  consumer-connector:
    image: local-connector
    build:
      context: ../src/launchers/default
      args:
        JAR: build/libs/connector.jar
      dockerfile: Dockerfile
      
    environment:
      EDC_FS_CONFIG: /app/configuration.properties
      EDC_API_AUTH_KEY: "fifi-info-zaneta"
      
    ports:
      - '29191:29191'
      - '29192:29192'
      - '29193:29193'
      - '29194:29194'
      - '29291:29291'
    
    volumes:
      - ../src/launchers/default/config/configuration-consumer.properties:/app/configuration.properties:ro
      - ../src/launchers/default/config/keystore.pfx:/app/keystore.pfx:ro
      - ../src/launchers/default/config/fs-consumer.vault:/app/fs.vault

